#!/bin/bash

# move working directory to script's directory
cd "${0%/*}"

echo "==>>>=======>>=====<+>=======<<========<<<=="
echo "*** National Geographic Photo of The Day ***"
echo "==>>>=======>>=====<+>=======<<========<<<=="

echo "# Install script"
cp ngpd /usr/local/bin/ngpd
cp com.yuan.ngpd.plist ~/Library/LaunchAgents/com.yuan.ngpd.plist

if [ ! -e ~/Pictures/ngpd ]; then
echo "# Create directory at ~/Pictures/ngpd"
mkdir ~/Pictures/ngpd
fi
echo "# Load agent and run"
launchctl load ~/Library/LaunchAgents/com.yuan.ngpd.plist

# Print "have a nice day"
python print.py
