#!/bin/bash

# move working directory to script's directory
cd "${0%/*}"

echo "==>>>=======>>=====<+>=======<<========<<<=="
echo "*** National Geographic Photo of The Day ***"
echo "==>>>=======>>=====<+>=======<<========<<<=="

echo "# Installing enviornment:"
if [ ! -e /usr/local/Homebrew ]; then
echo "# Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "# Updating Homebrew"
brew update

if [ ! -e /usr/local/bin/wget ]; then
echo "# Installing wget"
brew install wget
fi

echo "# Installing script:"
echo "# Installing files"
cp ngpd /usr/local/bin/ngpd
cp com.yuan.ngpd.plist ~/Library/LaunchAgents/com.yuan.ngpd.plist

if [ ! -e ~/Pictures/ngpd ]; then
echo "# Create directory at ~/Pictures/ngpd"
mkdir ~/Pictures/ngpd
fi
echo "# Load agent and run"
launchctl load ~/Library/LaunchAgents/com.yuan.ngpd.plist

# Print "have a nice day"
python print.py
