#!/bin/bash

PICTURES_DIR=~/Pictures/ngpd

# ====================
# =     FUNCTION     =
# ====================

function get_page {
echo "# Get website page for url"
curl --silent -o - http://www.nationalgeographic.com/photography/photo-of-the-day/ | grep -m 1 http://yourshot.nationalgeographic.com/u/.*/ -o > /tmp/pic_url
}

function clean_up {
echo "# Clean up temporary files"
if [ -e "/tmp/pic_url" ]; then
    rm /tmp/pic_url
fi
}

# ====================
# =       MAIN       =
# ====================


TODAY=$(date +'%Y%m%d')

if [ ! -e $PICTURES_DIR/ ]; then
    echo "# First time using, setting up."
    mkdir $PICTURES_DIR
fi

get_page

PICURL=`/bin/cat /tmp/pic_url`
PICURL="${PICURL:0:${#PICURL} - 2}"

# "Picture URL is: $PICURL"

echo "# Download picture"
curl --silent $PICURL -o $PICTURES_DIR/${TODAY}_NGPD.jpeg

echo "# Set picture as wallpaper"
osascript -e "tell application \"Finder\" to set desktop picture to \"$PICTURES_DIR/${TODAY}_NGPD.jpeg\" as POSIX file"

clean_up
date >> /tmp/timelog.log
# say "Job's done."
