#!/bin/bash

PICTURES_DIR=~/Pictures/ngpd

# ====================
# =     FUNCTION     =
# ====================

# keep getting url until get the valuable url(not nil)
function get_page {
echo "# Get website page for url"
URL=""
until [ URL != "" ]
do
URL=`wget --quiet -O - http://www.nationalgeographic.com/photography/photo-of-the-day/ | grep -m 1 http://yourshot.nationalgeographic.com/u/.*/ -o`
done
URL="${URL:0:${#URL} - 2}"
return URL
}

function clean_up {
echo "# Clean up temporary files"
if [ -e "/tmp/ngpd_ept.jpg" ]; then
rm /tmp/ngpd_ept.jpg
fi
}

# ====================
# =       MAIN       =
# ====================

TODAY=$(date +'%Y%m%d')

if [ ! -e $PICTURES_DIR/ ]; then
echo "# First time to use, setting up."
mkdir $PICTURES_DIR
fi

PICURL=get_page

# echo "Picture URL is: $PICURL"

echo "# Download picture"
wget --quiet $PICURL -O $PICTURES_DIR/${TODAY}_NGPD.jpg
PICURL=get_page

chmod 666 $PICTURES_DIR/${TODAY}_NGPD.jpg
# Save picture for export to desktop picture, for osascript would not take substutution of variable
cp $PICTURES_DIR/${TODAY}_NGPD.jpg /tmp/ngpd_ept.jpg


echo "# Set picture as wallpaper"
osascript -e 'tell application "Finder" to set desktop picture to "/tmp/ngpd_ept.jpg" as POSIX file'

clean_up
