#!/bin/bash

echo "# Unload agent"
launchctl unload ~/Library/LaunchAgents/ngpd_uni.plist

echo "# Deleting files"
rm /usr/local/bin/ngpd
rm ~/Library/LaunchAgents/ngpd_uni.plist
rm ~/Pictures/ngpd
rm /tmp/timelog.log
rm /tmp/ept
echo "# Uninstall done"
